Description: Deploys a Lambda function that creates GitHub Actions runner registration tokens using a GitHub App.

Parameters:
  GitHubRunnerTokenLambdaArn:
    Type: String
    Description: GitHub runner token Lambda ARN

Resources:

  # Permission for EC2 instances
  AllowEC2InvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        !Ref GitHubRunnerTokenLambdaArn
      Action:
        lambda:InvokeFunction
      Principal:
        ec2.amazonaws.com