Description: Deploys an EC2 Image Builder Pipeline that creates a self-hosted GitHub Actions runner for Unreal Engine.

Parameters:
  ResourceName:
    Type: String
    Default: WindowsServer2025-Unreal-Engine
    Description: A name to use for all Image Builder resources

  InstanceType:
    Type: String
    Description: EC2 instance type used during image build

  FilesBucketName:
    Type: String
    Description: Name of the S3 bucket for Unreal Engine files

  UnrealMajorVersion:
    Type: String
    Description: Unreal Engine major version

  UnrealMinorVersion:
    Type: String
    Description: Unreal Engine minor version

  SnsTopicArn:
    Type: String
    Description: SNS topic ARN for notifications


Resources:
  # EC2 instance role
  # By default, AWS Services do not have permission to perform actions on your instances. This grants
  # AWS Systems Manager (SSM) and EC2 Image Builder the necessary permissions to build an image.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  # https://docs.aws.amazon.com/imagebuilder/latest/userguide/image-builder-setting-up.html
  InstanceRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: Role to be used by instance during image build.
    Properties:
      RoleName: !Sub ${ResourceName}-${UnrealMajorVersion}.${UnrealMinorVersion}-InstanceRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'ec2.${AWS::URLSuffix}'
      Path: /executionServiceEC2Role/


  # EC2 instance role logging policy
  # Policy to allow the instance to write to the S3 bucket (via instance role / instance profile).
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
  InstanceRoleLoggingPolicy:
    Type: AWS::IAM::Policy
    Metadata:
      Comment: Allows the instance to save log files to an S3 bucket.
    Properties:
      PolicyName: !Sub ${ResourceName}-${UnrealMajorVersion}.${UnrealMinorVersion}-InstanceRoleLoggingPolicy
      Roles:
        - Ref: InstanceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Join ['', [!ImportValue ImageBuilderLogBucketArn '/*']]


  # EC2 instance role files bucket policy
  # Policy to allow the instance to download Unreal Engine files
  InstanceFilesBucketPolicy:
    Type: AWS::IAM::Policy
    Metadata:
      Comment: Allows the instance to download files from an S3 bucket.
    Properties:
      PolicyName: !Sub ${ResourceName}-${UnrealMajorVersion}.${UnrealMinorVersion}-InstanceFilesBucketPolicy
      Roles:
        - Ref: InstanceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - Fn::Sub: arn:${AWS::Partition}:s3:::${FilesBucketName}/*


  # EC2 instance profile
  # To pass the InstanceRole to an EC2 instance, we need an InstanceProfile.
  # This profile will be used during the image build process.
  # https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${ResourceName}-${UnrealMajorVersion}.${UnrealMinorVersion}-InstanceProfile
      Roles:
        - Ref: InstanceRole


  # Build instance configuration
  # Specifies the infrastructure within which to build and test your image.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-infrastructureconfiguration.html
  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: !Sub ${ResourceName}-${UnrealMajorVersion}-${UnrealMinorVersion}-BuildInfrastructure
      InstanceTypes:
        - !Ref InstanceType
      InstanceProfileName:
        Ref: InstanceProfile
      SnsTopicArn: !Ref SnsTopicArn
      # Specify an S3 bucket and EC2 Image Builder will save logs to the bucket.
      Logging:
        S3Logs:
          S3BucketName: !Join ['', [!ImportValue ImageBuilderLogBucketArn '/*']]
#           S3KeyPrefix: 'my-imagebuilder-bucket-prefix'
      # If you would like to keep the instance running after a failed build, set TerminateInstanceOnFailure to false.
      # TerminateInstanceOnFailure: false
      # If you do not have a default VPC or want to use a different VPC, you must specify the subnet ID to use
      # SubnetId: 'subnet-id'
  

  # Custom component to install Unreal Engine
  UnrealEngineComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub Install-Unreal-Engine-${UnrealMajorVersion}-${UnrealMinorVersion}
      Description: !Sub Installs Unreal Engine ${UnrealMajorVersion}.${UnrealMinorVersion}
      Platform: Windows
      Version: 1.0.0
      ChangeDescription: Initial Unreal Engine component

      Data: !Sub |
        name: Install Unreal Engine
        description: Downloads and extracts Unreal Engine
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: DownloadUnrealEngine
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      $ErrorActionPreference = "Stop"
                      $ZipFilePath = "C:\Windows\Temp\UnrealEngine.zip"
        
                      Write-Host "Downloading Unreal Engine binaries..."
                      Read-S3Object -BucketName unreal-build-server-files -Key UE_${UnrealMajorVersion}.${UnrealMinorVersion}.zip -File $ZipFilePath
        
                      if (!(Test-Path $ZipFilePath)) {
                        throw "Unreal Engine download failed"
                      }
        
              - name: ExtractUnrealEngine
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      $ErrorActionPreference = "Stop"
                      $7ZipExePath = "C:\Program Files\7-Zip\7z.exe"
                      $ZipFilePath = "C:\Windows\Temp\UnrealEngine.zip"

                      Write-Host "Extracting Unreal Engine binaries..."
                      & $7ZipExePath x -o"C:\Program Files\Epic Games\" $ZipFilePath -y
                      Remove-Item -Path $ZipFilePath -Force
        
              - name: SetFolderPermissions
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      icacls "C:\Program Files\Epic Games\UE_${UnrealMajorVersion}.${UnrealMinorVersion}" /grant "NT AUTHORITY\NETWORK SERVICE:(OI)(CI)M" /T /C
        
              - name: VerifyUnrealEngine
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      $ErrorActionPreference = "Stop"
                      $UnrealPath = "C:\Program Files\Epic Games\UE_${UnrealMajorVersion}.${UnrealMinorVersion}\"

                      Write-Host "Verifying Unreal Engine extraction..."

                      if (!(Test-Path $UnrealPath)) {
                          throw "Unreal Engine directory not found at $UnrealPath"
                      }

                      $RunUatBatch = Join-Path $UnrealPath "\Engine\Build\BatchFiles\RunUAT.bat"
        
                      if (!(Test-Path $RunUatBatch)) {
                          throw "RunUAT.bat not found - extraction may have failed"
                      }

                      Write-Host "Unreal Engine verified successfully at $UnrealPath"


  # Windows Server 2025 base image
  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Sub ${ResourceName}-${UnrealMajorVersion}-${UnrealMinorVersion}
      Version: 1.0.0
      ParentImage: !ImportValue UnrealBuildServerBaseImage
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 250
            VolumeType: gp3
      Components:
        - ComponentArn: !Ref UnrealEngineComponent


  # AMI distribution
  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: !Sub ${ResourceName}-${UnrealMajorVersion}-${UnrealMinorVersion}
      Distributions:
        - Region:
            Ref: AWS::Region
          AmiDistributionConfiguration:
            Name: !Sub ${ResourceName}-${UnrealMajorVersion}-${UnrealMinorVersion}-{{imagebuilder:buildDate}}
            Description: !Sub Windows Server 2025 with Unreal Engine ${UnrealMajorVersion}.${UnrealMinorVersion} installed
            AmiTags:
              UnrealEngineVersion: !Sub "${UnrealMajorVersion}.${UnrealMinorVersion}"


  # Image pipeline
  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: !Sub ${ResourceName}-${UnrealMajorVersion}-${UnrealMinorVersion}-Pipeline
      ImageRecipeArn:
        Ref: ImageRecipe
      InfrastructureConfigurationArn:
        Ref: InfrastructureConfiguration
      DistributionConfigurationArn:
        Ref: DistributionConfiguration
      Status:
        ENABLED


Outputs:
  ImageBuilderPipelineArn:
    Description: Image Builder Pipeline ARN
    Value:
      Ref: ImagePipeline