Parameters:
  LogBucketName:
    Type: String
    Description: Name of the S3 bucket for image builder logs

  InstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type used during image build

  UnrealMajorVersion:
    Type: String
    Default: 5
    Description: Unreal Engine major version

  UnrealMinorVersion:
    Type: String
    Default: 6
    Description: Unreal Engine minor version

  SnsTopicArn:
    Type: String
    Description: SNS topic ARN for notifications

Resources:
  # Image builder log bucket
  ImageBuilderLogBucket:
    Type: AWS::S3::Bucket
    # If you want to delete the stack, but keep the bucket, set the DeletionPolicy to Retain.
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Ref LogBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # EC2 instance role
  # By default, AWS Services do not have permission to perform actions on your instances. This grants
  # AWS Systems Manager (SSM) and EC2 Image Builder the necessary permissions to build an image.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  # https://docs.aws.amazon.com/imagebuilder/latest/userguide/image-builder-setting-up.html
  InstanceRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: Role to be used by instance during image build.
    Properties:
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'ec2.${AWS::URLSuffix}'
      Path: /executionServiceEC2Role/

  # EC2 instance role logging policy
  # Policy to allow the instance to write to the S3 bucket (via instance role / instance profile).
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
  InstanceRoleLoggingPolicy:
    Type: AWS::IAM::Policy
    Metadata:
      Comment: Allows the instance to save log files to an S3 bucket.
    Properties:
      PolicyName: ImageBuilderLogBucketPolicy
      Roles:
        - Ref: InstanceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource:
              - Fn::Sub:
                  - arn:${AWS::Partition}:s3:::${BUCKET}/*
                  - BUCKET:
                      Ref: ImageBuilderLogBucket

  # EC2 instance profile
  # To pass the InstanceRole to an EC2 instance, we need an InstanceProfile.
  # This profile will be used during the image build process.
  # https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: UnrealBuildServerImageInstanceProfile
      Roles:
        - Ref: InstanceRole

  # Build instance configuration
  # Specifies the infrastructure within which to build and test your image.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-infrastructureconfiguration.html
  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: WindowsServer2025-BuildInfrastructure
      InstanceTypes:
        - !Ref InstanceType
      InstanceProfileName:
        Ref: InstanceProfile
      SnsTopicArn: !Ref SnsTopicArn
      # Specify an S3 bucket and EC2 Image Builder will save logs to the bucket.
      Logging:
        S3Logs:
          S3BucketName:
            Ref: ImageBuilderLogBucket
          # S3KeyPrefix: 'my-imagebuilder-bucket-prefix'
      # If you would like to keep the instance running after a failed build, set TerminateInstanceOnFailure to false.
      # TerminateInstanceOnFailure: false
      # If you do not have a default VPC or want to use a different VPC, you must specify the subnet ID to use
      # SubnetId: 'subnet-id'

  # Custom component to install Git
  GitComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Install-Git
      Version: 1.0.0
      Description: Install Git for Windows
      Platform: Windows
      Data: |
        name: Install Git for Windows
        description: Installs Git using the official Git for Windows installer
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: DownloadGit
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      $url = "https://github.com/git-for-windows/git/releases/download/v2.55.0.windows.2/Git-2.55.0.2-64-bit.exe"
                      $installer = "C:\Windows\Temp\GitInstaller.exe"
                      Invoke-WebRequest `
                        -Uri $url `
                        -OutFile $installer

              - name: InstallGit
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      Start-Process `
                        -FilePath "C:\Windows\Temp\GitInstaller.exe" `
                        -ArgumentList "/VERYSILENT /NORESTART" `
                        -Wait


              - name: VerifyGit
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      git --version

  # Custom component to install Git LFS
  GitLfsComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Install-Git-LFS
      Version: 1.0.0
      Description: Install Git LFS for Windows
      Platform: Windows
      Data: |
        name: Install Git for Windows
        description: Installs Git LFS using the official Git LFS for Windows installer
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: DownloadGitLfs
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      $url = "https://github.com/git-lfs/git-lfs/releases/download/v3.4.0/git-lfs-windows-v3.4.0.exe"
                      $installer = "C:\Windows\Temp\GitLfsInstaller.exe"
                      Invoke-WebRequest `
                        -Uri $url `
                        -OutFile $installer

              - name: InstallGitLfs
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      Start-Process `
                        -FilePath "C:\Windows\Temp\GitLfsInstaller.exe" `
                        -ArgumentList "/SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART" `
                        -Wait


              - name: VerifyGitLfs
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      git lfs --version

  # Custom component to install Visual Studio 2026 Community Edition
  VisualStudio2026CommunityComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Install-VisualStudio-2026-Community
      Platform: Windows
      Version: 1.0.0
      Description: Installs Visual Studio 2026 Community Edition
      Data: |
        name: Install Visual Studio 2026 Community
        description: Downloads and installs Visual Studio 2026 Community
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: InstallVisualStudio
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      $ErrorActionPreference = "Stop"

                      $InstallerPath = "C:\Windows\Temp\vs_community.exe"

                      Write-Host "Downloading Visual Studio Community installer..."

                      Invoke-WebRequest `
                        -Uri "https://aka.ms/vs/18/release/vs_community.exe" `
                        -OutFile $InstallerPath

                      Write-Host "Installing Visual Studio..."

                      Start-Process `
                        -FilePath $InstallerPath `
                        -ArgumentList @(
                          "--quiet",
                          "--wait",
                          "--norestart",
                          "--nocache",
                          "--add",
                          "Microsoft.VisualStudio.Workload.NativeGame",
                          "--includeRecommended"
                        ) `
                        -Wait `
                        -PassThru

                      if ($LASTEXITCODE -ne 0) {
                          throw "Visual Studio installation failed with exit code $LASTEXITCODE"
                      }

                      Write-Host "Cleaning up installer..."

                      Remove-Item `
                        -Path $InstallerPath `
                        -Force

                      Write-Host "Visual Studio installation complete."
        
              - name: VerifyVisualStudio
                action: ExecutePowerShell
                inputs:
                  commands:
                    - |
                      if (!(Test-Path "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\devenv.exe")) {
                          throw "Visual Studio not detected"
                      }

  # Windows Server 2025 base image
  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name:
        Fn::Sub:
          WindowsServer2025-Unreal-Engine-${UnrealMajorVersion}-${UnrealMinorVersion}
      Version: 1.0.0
      # ${AWS::Partition} returns the partition where you are running the CloudFormation template. For standard AWS regions, the
      # partition is aws. For resources elsewhere, the partition is aws-partitionname. For example, China (Beijing and Ningxia)
      # regions use aws-cn and AWS GovCloud (US) regions are aws-us-gov.
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html
      ParentImage:
        Fn::Sub:
          arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:image/windows-server-2025-english-full-base-x86/x.x.x
      Components:
        - ComponentArn: !Ref GitComponent
        - ComponentArn: !Ref GitLfsComponent
        - ComponentArn: !Ref VisualStudio2026CommunityComponent

  # AMI distribution
  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name:
        Fn::Sub:
          WindowsServer2025-Unreal-Engine-${UnrealMajorVersion}-${UnrealMinorVersion}
      Distributions:
        - Region:
            Ref: AWS::Region
          AmiDistributionConfiguration:
            Name:
              Fn::Sub:
                WindowsServer2025-Unreal-Engine-${UnrealMajorVersion}-${UnrealMinorVersion}-{{imagebuilder:buildDate}}
            Description:
              Windows Server 2025 with Unreal Engine ${UnrealMajorVersion}.${UnrealMinorVersion} installed

  # Image pipeline
  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name:
        Fn::Sub:
          WindowsServer2025-Unreal-Engine-${UnrealMajorVersion}-${UnrealMinorVersion}-Pipeline
      ImageRecipeArn:
        Ref: ImageRecipe
      InfrastructureConfigurationArn:
        Ref: InfrastructureConfiguration
      DistributionConfigurationArn:
        Ref: DistributionConfiguration
      Status:
        ENABLED

Outputs:
  PipelineArn:
    Description: Image Builder Pipeline ARN
    Value:
      Ref: ImagePipeline