Description: Deploys an S3 bucket for as a destination for EC2 Image Builder logs.

Parameters:
  LogBucketName:
    Type: String
    Description: Name of the S3 bucket for EC2 Image Builder logs

Resources:
  # Image builder log bucket
  ImageBuilderLogBucket:
    Type: AWS::S3::Bucket
    # If you want to delete the stack, but keep the bucket, set the DeletionPolicy to Retain.
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref LogBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

Outputs:
  ImageBuilderLogBucketName:
    Description: Image Builder Log S3 Bucket Name
    Value: !GetAtt ImageBuilderLogBucket.BucketName
    Export:
      Name: ImageBuilderLogBucketName