Resources:
  InfrastructureRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: Role to be used by AWS Services to perform actions on your instances.
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:sawnoff-studios/unreal-build-server-image:*
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AWSCloudFormationFullAccess
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AWSLambda_FullAccess
      Policies:
        - PolicyName: UnrealBuildServerImageDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateInstanceProfile
                  - iam:DeleteInstanceProfile
                  - iam:CreatePolicy
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:DeletePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:AddRoleToInstanceProfile
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:GetRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:CreateServiceLinkedRole
                  - iam:PassRole
                  - iam:GetRole
                  - iam:TagRole
                  - iam:GetInstanceProfile
                  - imagebuilder:CreateDistributionConfiguration
                  - imagebuilder:CreateComponent
                  - imagebuilder:CreateImagePipeline
                  - imagebuilder:CreateInfrastructureConfiguration
                  - imagebuilder:CreateImageRecipe
                  - imagebuilder:DeleteDistributionConfiguration
                  - imagebuilder:DeleteComponent
                  - imagebuilder:DeleteImagePipeline
                  - imagebuilder:DeleteInfrastructureConfiguration
                  - imagebuilder:DeleteImageRecipe
                  - imagebuilder:GetComponent
                  - imagebuilder:GetImageRecipe
                  - imagebuilder:GetInfrastructureConfiguration
                  - imagebuilder:GetDistributionConfiguration
                  - imagebuilder:UpdateInfrastructureConfiguration
                  - imagebuilder:UpdateDistributionConfiguration
                  - imagebuilder:StartImagePipelineExecution
                  - SNS:Publish
                  - secretsmanager:CreateSecret
                  - secretsmanager:GetSecretValue
                  - secretsManager:DeleteSecret
                  - secretsManager:UpdateSecret
                Resource: "*"
