AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a Lambda function that creates GitHub Actions runner registration tokens using a GitHub App.

Parameters:
  GitHubOrganisation:
    Type: String
    Description: GitHub organisation name

  SecretsManagerKeyName:
    Type: String
    Description: Secrets Manager key containing GitHub App credentials

  GitHubAppId:
    Type: String
    Description: GitHub App ID

  GitHubAppInstallationId:
    Type: String
    Description: GitHub App installation ID

  GitHubAppPrivateKey:
    Type: String
    Description: GitHub App private key

Resources:
  # Secrets Manager Secret
  GitHubRunnerAppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretsManagerKeyName

      Description:
        GitHub App credentials for Actions runner registration

      SecretString: !Sub
        |
        {
          "app_id": "${GitHubAppId}",
          "installation_id": "${GitHubAppInstallationId}",
          "private_key": "${GitHubAppPrivateKey}"
        }

  # Lambda function
  GitHubRunnerTokenLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: github-runner-token
      Description: Creates GitHub Actions runner registration tokens using a GitHub App
      Runtime: nodejs24.x
      Handler: index.handler
      Timeout: 30
      MemorySize: 128
      CodeUri: runner-token/
      Environment:
        Variables:
          SECRETS_MANAGER_KEY_NAME: !Ref SecretsManagerKeyName
          GITHUB_ORGANISATION: !Ref GitHubOrganisation
      Policies:
        - PolicyName: GitHubRunnerTokenLambdaGetSecretValue
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref GitHubRunnerAppSecret
        - AWSLambdaBasicExecutionRole


Outputs:
  RunnerTokenLambdaArn:
    Description: Lambda ARN
    Value: !GetAtt GitHubRunnerTokenLambda.Arn