name: Deploy Runner Token Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - runner-token/**

env:
  PROJECT_NAME: "UnrealBuildServerRunnerTokenLambda"
  AWS_REGION: "ap-southeast-2"
  GITHUB_ORG: "sawnoff-studios"

permissions:
  id-token: write
  contents: read

jobs:
  DeployLambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: ${{ env.PROJECT_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v2
        id: deploy
        with:
          name: ${{ env.PROJECT_NAME }}Stack
          template: ${{ github.workspace }}/runner-token-lambda-infra.yml
          parameter-overrides: "GitHubOrganization=${{ env.GITHUB_ORG }},SecretAppId=${{ secrets.LAMBDA_APP_ID }},InstallationId=${{ secrets.LAMBDA_APP_INSTALLATION_ID }},PrivateKey=${{ secrets.LAMBDA_APP_PRIVATE_KEY }}"

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: gitHub-runner-token
          code-artifacts-dir: ./runner-token
          handler: index.handler
          role: ${{ steps.deploy.outputs.LambdaArn  }}
          environment: '{ "GITHUB_SECRET": "${{ secrets.GITHUB_TOKEN }}", "GITHUB_ORG": "${{ env.GITHUB_ORG }}" }'
          timeout: 30
          memory-size: 128