name: Deploy Image Build Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy EC2 Image Builder Components"]
    types: [completed]
  push:
    branches:
      - main
    paths:
      - "image-pipeline-infra.yml"

env:
  PROJECT_NAME: "Unreal55BuildServerImage"
  AWS_REGION: "ap-southeast-2"
  INSTANCE_TYPE: "c5.xlarge"
  LOG_BUCKET_NAME: "unreal-build-server-image-logs"
  FILES_BUCKET_NAME: "unreal-build-server-files"
  UNREAL_MAJOR_VERSION: "5"
  UNREAL_MINOR_VERSION: "4"
  RUNNER_TOKEN_LAMBDA_STACK_NAME: "UnrealBuildServerRunnerTokenLambdaStack"
  COMPONENTS_STACK_NAME: "UnrealBuildServerImageComponentsStack"

permissions:
  id-token: write
  contents: read

jobs:
  DeployStack:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: ${{ env.PROJECT_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Clone repository
        uses: actions/checkout@v7

      - name: Get runner token Lambda ARN
        id: get-runner-token-lambda-arn
        run: |
          RUNNER_TOKEN_LAMBDA_ARN=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.RUNNER_TOKEN_LAMBDA_STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='LambdaArn'].OutputValue" \
            --output text)
          
          echo "LAMBDA_ARN=$RUNNER_TOKEN_LAMBDA_ARN" >> $GITHUB_OUTPUT

      - name: Get component ARNs
        id: get-component-arns
        run: |
          AWS_CLI_COMPONENT_ARN=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.COMPONENTS_STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='ComponentArn'].OutputValue" \
            --output text)
          
          CLOUD_WATCH_AGENT_COMPONENT_ARN=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.COMPONENTS_STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='CloudWatchAgentComponentArn'].OutputValue" \
            --output text)
          
          SEVEN_ZIP_COMPONENT_ARN=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.COMPONENTS_STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='7ZipComponentArn'].OutputValue" \
            --output text)
          
          GIT_COMPONENT_ARN=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.COMPONENTS_STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='GitComponentArn'].OutputValue" \
            --output text)
          
          GITHUB_ACTIONS_RUNNER_COMPONENT_ARN=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.COMPONENTS_STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='GitHubActionsRunnerComponentArn'].OutputValue" \
            --output text)
          
          VISUAL_STUDIO_COMPONENT_ARN=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.COMPONENTS_STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='VisualStudioComponentArn'].OutputValue" \
            --output text)
          
          echo "AWS_CLI_COMPONENT_ARN=$AWS_CLI_COMPONENT_ARN" >> $GITHUB_OUTPUT
          echo "CLOUD_WATCH_AGENT_COMPONENT_ARN=$CLOUD_WATCH_AGENT_COMPONENT_ARN" >> $GITHUB_OUTPUT
          echo "SEVEN_ZIP_COMPONENT_ARN=$SEVEN_ZIP_COMPONENT_ARN" >> $GITHUB_OUTPUT
          echo "GIT_COMPONENT_ARN=$GIT_COMPONENT_ARN" >> $GITHUB_OUTPUT
          echo "GITHUB_ACTIONS_RUNNER_COMPONENT_ARN=$GITHUB_ACTIONS_RUNNER_COMPONENT_ARN" >> $GITHUB_OUTPUT
          echo "VISUAL_STUDIO_COMPONENT_ARN=$VISUAL_STUDIO_COMPONENT_ARN" >> $GITHUB_OUTPUT

      - name: Remove existing CloudFormation stack
        run: |
          aws cloudformation delete-stack --stack-name ${{ env.PROJECT_NAME }}Stack
          aws cloudformation wait stack-delete-complete --stack-name ${{ env.PROJECT_NAME }}Stack

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v2
        id: deploy
        with:
          name: ${{ env.PROJECT_NAME }}Stack
          template: ${{ github.workspace }}/image-pipeline-infra.yml
          parameter-overrides: "InstanceType=${{ env.INSTANCE_TYPE }},\
            LogBucketName=${{ env.LOG_BUCKET_NAME }},\
            FilesBucketName=${{ env.FILES_BUCKET_NAME }},\
            UnrealMajorVersion=${{ env.UNREAL_MAJOR_VERSION }},\
            UnrealMinorVersion=${{ env.UNREAL_MINOR_VERSION }},\
            SnsTopicArn=${{ secrets.SNS_TOPIC_ARN }},\
            RunnerTokenLambdaArn=${{ steps.get-runner-token-lambda-arn.outputs.LAMBDA_ARN }},\
            AwsCliComponentArn=${{ steps.get-component-arns.outputs.AWS_CLI_COMPONENT_ARN }},\
            CloudWatchComponentArn=${{ steps.get-component-arns.outputs.CLOUDWATCH_COMPONENT_ARN }},\
            SevenZipComponentArn=${{ steps.get-component-arns.outputs.SEVEN_ZIP_COMPONENT_ARN }},\
            GitComponentArn=${{ steps.get-component-arns.outputs.GIT_COMPONENT_ARN }},\
            GitHubActionsRunnerComponentArn=${{ steps.get-component-arns.outputs.GITHUB_ACTIONS_RUNNER_COMPONENT_ARN }},\
            VisualStudioComponentArn=${{ steps.get-component-arns.outputs.VISUAL_STUDIO_COMPONENT_ARN }}"
          capabilities: 'CAPABILITY_NAMED_IAM'