name: Deploy Runner Token Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-runner-token-lambda.yml"
      - "runner-token-lambda-infra.yml"
      - "runner-token/**"
      - "allow-ec2-invoke-lambda-infra.yml"

env:
  PROJECT_NAME: "UnrealBuildServerRunnerTokenLambda"
  AWS_REGION: "ap-southeast-2"
  LAMBDA_ZIP_FILE_PATH: "./lambda.zip"
  GITHUB_ORG: "sawnoff-studios"
  SECRETS_MANAGER_KEY_NAME: "/github/actions/runner-key"

permissions:
  id-token: write
  contents: read

jobs:
  DeployStack:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: ${{ env.PROJECT_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v3
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: SAM build
        run: sam build --use-container -t ${{ github.workspace }}/runner-token-lambda-infra.yml

      - name: SAM validate
        run: sam validate --template-file ${{ github.workspace }}/runner-token-lambda-infra.yml

      - name: SAM deploy
        run: sam deploy --template-file ${{ github.workspace }}/runner-token-lambda-infra.yml --stack-name ${{ env.PROJECT_NAME }}Stack --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides 'ParameterKey=GitHubOrganization,ParameterValue=${{ env.GITHUB_ORGANIZATION }}' 'ParamterKey=SecretsManagerKeyName,ParameterValue=${{ env.SECRETS_MANAGER_KEY_NAME }}' 'ParameterKey=GitHubAppAppId,ParameterValue=${{ secrets.LAMBDA_APP_ID }}' 'ParameterKey=GitHubAppInstallationId,ParameterValue=${{ secrets.LAMBDA_APP_INSTALLATION_ID }}' 'ParameterKey=GitHubAppPrivateKey,ParameterValue=${{ secrets.LAMBDA_APP_PRIVATE_KEY }}'